services:
  op-geth: # this is Optimism's geth client
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101603.5
    container_name: op-geth
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8545:8545       # HTTP RPC
      - 8546:8546       # Websocket
      - 30303:30303     # P2P TCP
      - 30303:30303/udp # P2P UDP
      - 6060:6060       # metrics
    env_file:
      - .env
    volumes:
      - /data/node_data:/data
      - ./config/genesis.json:/genesis.json
      - ./config/jwtsecret:/jwtsecret:ro
      - ./scripts/start-op-geth.sh:/scripts/start-op-geth.sh:ro
    entrypoint: ["/bin/sh", "/scripts/start-op-geth.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.16.2
    container_name: op-node
    pull_policy: always
    restart: unless-stopped
    ports:
      - 9545:9545     # HTTP RPC
      - 9222:9222     # P2P TCP
      - 9222:9222/udp # P2P UDP
      - 7300:7300     # metrics
    env_file:
      - .env
    volumes:
      - ./config/rollup.json:/rollup.json
      - ./config/genesis.json:/genesis.json
      - ./config/jwtsecret:/jwtsecret:ro
      - ./scripts/start-op-node.sh:/scripts/start-op-node.sh:ro
    entrypoint: ["/bin/sh", "/scripts/start-op-node.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
